title: "Linh Vu's Blog"
email: vulinhtnut@gmail.com
description: "Khoa học máy tính"
author: Linh Vu

# Base URL = để trống nếu deploy trên username.github.io
baseurl: "/Blog"
url: "https://vuthilinhvn.github.io"

# Social Profiles
twitter_username: linhvu
github_username: VuthilinhVn
facebook_username: linhvu
linkedin_username: linhvu

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

paginate: 5
paginate_path: "/posts/page:num/"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

