title:              Rodbate Blog
email:              rodbatejss@gmail.com
description:        Tech Blogs
author:             rodbate
baseurl:            "/rodbate.github.io"
url:                "https://rodbate.github.io"

# Social Profiles
twitter_username:   rodbate
github_username:    rodbate
facebook_username:  rodbate
linkedin_username:  rodbate

# Add your google-analytics ID here to activate google analytics
#google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
