title: "Linh Vu's Blog"
email: vulinhtnut@gmail.com
description: "Khoa Học Máy Tính"
author: Linh Vũ

# Base URL = để trống nếu deploy trên username.github.io
baseurl: "/Blog"
url: "https://vuthilinhvn.github.io"

# Social Profiles
github_username: https://github.com/VuthilinhVn/
facebook_username: https://www.facebook.com/linhpltn.98


# Build settings
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

paginate: 5
paginate_path: "/posts/page:num/"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

